sudo: required
language: generic
services:
  - docker
before_script:
  - docker --version
script:
  - docker build -t instantplus/coturn:latest .
notifications:
  email:
    recipients:
      - ivo@instant.plus
      - christian@instant.plus
